name: Cache Dependencies

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        # This ID is used to reference the outputs of this specific step
        id: cache-step 
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependencies
          key: cache-1ad7459

      - name: prime-cache-1ad7459
        # This step name must exist exactly as requested
        run: echo "Cache hit ${{ steps.cache-step.outputs.cache-hit }}"
